In [434]:
import numpy as np
import matplotlib.pyplot as plt

- NumPy’s main object is the homogeneous(only one type of data (numerical)) multidimensional array. It is a table of elements (usually numbers), all of the same type, INDEXED by a TUPLE of non-negative integers. In NumPy dimensions are called AXES.
- NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:


#### Prerequisites


    ndarray class


In [435]:
dir(np.ndarray)[-10:]

['take',
 'to_device',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

    attributes of ndarray class


In [436]:
data = np.array([12, 1, 34, 56])

In [437]:
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.itemsize)
print(data.data)

1
(4,)
4
int64
8


In [438]:
data = np.arange(15).reshape(3, 5)

In [439]:
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.itemsize)
print(data.data)

2
(3, 5)
15
int64
8


    Ways to create an array


In [440]:
a = np.array([1, 243, 5, 6, 7])
print(a, a.dtype)
b = np.array([121.3, 45.34, 5.6, 23.2])
print(b, b.dtype)

[  1 243   5   6   7] int64
[121.3   45.34   5.6   23.2 ] float64


In [441]:
b = np.array([(2, 13, 4, 5, 6), (12, 34, 5, 7, 7)])
print(b, b.dtype)

[[ 2 13  4  5  6]
 [12 34  5  7  7]] int64


In [442]:
c = np.array(
    [[1, 2], [2, 3]], dtype=complex
)  # np.array([(1,2),(2,3)], dtype=complex) This also works
print(c, c.dtype)

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]] complex128


    Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.


In [443]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [444]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [445]:
np.empty((2, 3))  # This creates a random matrix

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

    To create a sequence of numbers, Numpy proves the arange function which is analogous to the python built-in range function, but it returns and array


In [446]:
np.arange(10, 30, 5)  # Create values starting from 10 till 30 with the steps of 5

array([10, 15, 20, 25])

In [447]:
np.arange(0, 2, 0.3)  # Create values starting from 0 till 2 with the steps of 0.3

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

    When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:


In [448]:
np.linspace(0, 2, 9)  # Linspace gives the predefined steps of how many values we need

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [449]:
x = np.linspace(0, 2 * np.pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [450]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

we also have these functions - 

    array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, random.Generator.random, random.Generator.normal, fromfunction, fromfile

#### Printing arrays

- When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
  - the last axis is printed from left to right,
  - the second-to-last is printed from top to bottom,
  - the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
  - One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.


In [451]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [452]:
b = np.arange(6).reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [453]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [454]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


#### Basic operations


    Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.


In [455]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)

[0 1 2 3]


In [456]:
a - b

array([20, 29, 38, 47])

In [457]:
b**2

array([0, 1, 4, 9])

In [458]:
10 * np.sin(a)  # Trigonometric sin of a

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [459]:
a < 35

array([ True,  True, False, False])

    Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:


In [460]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [461]:
A * B  # Element wise product

array([[2, 0],
       [0, 4]])

In [462]:
A @ B #Matrix product

array([[5, 4],
       [3, 4]])

In [463]:
A.dot(B) #Another Matrix product

array([[5, 4],
       [3, 4]])

    Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [464]:
rg = np.random.default_rng(1) #create instance of default random number generator

In [465]:
a = np.ones((2,3), dtype=int) 
b = rg.random((2,3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [466]:
a *=3 # multiply every number by 3 save it in a variable itself
a

array([[3, 3, 3],
       [3, 3, 3]])

In [467]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [468]:
# a+=b  # b is not automatically converted to integer type
# a 

    When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [469]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,np.pi, 3)
print(a)
print(b)

[1 1 1]
[0.         1.57079633 3.14159265]


In [470]:
c= a+b #this will converted to float
print(c)

[1.         2.57079633 4.14159265]


In [471]:
(c).dtype

dtype('float64')

In [472]:
d = np.exp(c*1j)
print(d)
print(d.dtype)

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


    Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [473]:
a= rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [474]:
a.sum()

np.float64(3.1057109529998157)

In [475]:
a.min()

np.float64(0.027559113243068367)

In [476]:
a.max()

np.float64(0.8277025938204418)

    By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [477]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [478]:
b.sum(axis=0) #sum of all the values in each column, Because it is sum ALONG axis 0

array([12, 15, 18, 21])

In [479]:
b.sum(axis=1) #Sum of all the values in each row, because it is sum ALONG axis 1

array([ 6, 22, 38])

In [480]:
b.min(axis=0) #This will give the row with the smallest values

array([0, 1, 2, 3])

In [481]:
b.min(axis=1) #This will give the columns with the smallest values

array([0, 4, 8])

In [482]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

#### Universal functions

    NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [483]:
B = np.arange(3)
B

array([0, 1, 2])

In [484]:
np.exp(B) #3 raise to the power that number elementwise

array([1.        , 2.71828183, 7.3890561 ])

In [485]:
np.sqrt(B) #Square root of that number

array([0.        , 1.        , 1.41421356])

In [486]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

We also have these below functons - 

    all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

#### Indexing, Slicing and Iterating

    One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [487]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
print(a[0:6:2]) #0 to 6 at the steps of 2
print(a[:6:2])
print(a)
print(a[-1]) #first item from last
print(a[::-1]) #Reverse the array
for i in a:
    print(i**(1 / 3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[ 0  8 64]
[ 0  8 64]
[  0   1   8  27  64 125 216 343 512 729]
729
[729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


    Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [490]:
def f(x, y):
    return 10*x+y

b = np.fromfunction(f,(5,4), dtype=int)
print(b)
print(b[2,3]) #Give me 2nd row's third column
print(b[0:5,1]) #give me all the 5 row's 1st column
print(b[:,1]) #give me all the rows of first column
print(b[1:3,:]) #give me all the columns of row 1 and 2

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


<p style="color: yellow; font-size:20px">Note: </p>When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
b[-1] #this is equivalent to b[-1, :]

array([40, 41, 42, 43])

    The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

x[1, 2, ...] is equivalent to x[1, 2, :, :, :],

x[..., 3] to x[:, :, :, :, 3] and

x[4, ..., 5, :] to x[4, :, :, 5, :].

In [492]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [499]:
c[1,...] # same as c[1, :, :] or c[1]
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

    Iterating over multidimensional arrays is done with respect to the first axis:

In [500]:
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [502]:
for row in b:
    print(row) #prints each row
    print("-"*10)

[0 1 2 3]
----------
[10 11 12 13]
----------
[20 21 22 23]
----------
[30 31 32 33]
----------
[40 41 42 43]
----------


    However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [503]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


#### Shape manipulation